export const END_POINT = {
  EXAMPLE: "/api/example",
  MY_INFO: "/api/users/my",
  BOOTCAMPS: "/api/bootcamps",
  BOOTCAMP_CATEGORIES: "/api/bootcamps/categories",
  BOOTCAMP_JOB_ROLES: "/api/job-roles",
  COURSES_AUTOCOMPLETE: "/api/courses/autocomplete",
  MY_REVIEWS: "/api/reviews/my",
  POINT_HISTORY: "api/points/my",
  COURSES: "api/courses/autocomplete",
  CERTIFICATE: "/api/users/my/certification",
  MENTOR_LIST: "/api/coffee-chats/info/search",
  APPROVED_COFFEE_CHATS: "/api/coffee-chats/applications/approved",
  FILE_UPLOAD: "/api/file/upload",
  SENT_COFFEE_CHATS: "/api/coffee-chats/applications",
  RECEIVED_COFFEE_CHATS: "/api/coffee-chats/applications/received",
  RECEIVED_CANCEL: (coffeeChatAppId: string) =>
    `/api/coffee-chats/applications/${coffeeChatAppId}/cancel`,
  STATUS_CHATS: (coffeeChatAppId: string) =>
    `/api/coffee-chats/applications/received/${coffeeChatAppId}/status`,
  BOOTCAMP_DETAIL: (id: string) => `/api/bootcamps/${id}`,
  REVIEWS: "/api/reviews",
  MENTOR_REGISTER: "/api/coffee-chats",
  MENTOR_APPLICATION_TIME: (coffeeChatInfoId: string) =>
    `/api/coffee-chats/${coffeeChatInfoId}/times`,
  NOTIFICATIONS: "/api/notifications",
  CHAT_ROOM: (roomUuid: string) => `/chat-rooms/${roomUuid}`,
  CHAT_ROOM_LIST: "/api/chat-rooms",
  CHAT_MESSAGE: (roomUuid: string) => `/api/chat-rooms/${roomUuid}/messages`,
  ADMIN_CERTIFICATION: "/api/admin/certifications",
  BOOTCAMPS_AUTOCOMPLETE: "/api/bootcamps/autocomplete",
  NAVER_REDIRECT: "/api/oauth2/authorization",
  LOGOUT: "/api/logout",
  UPDATE_REVIEW: (reviewId: number) => `/api/reviews/my/${reviewId}`,
  DELETE_REVIEW: (reviewId: number) => `/api/reviews/my/${reviewId}`,
  SSE_CONNECT: "/api/sse-connect",
  MARK_ALL_AS_READ: (time: string) => `/api/notifications?time=${time}`,
  MY_POINTS: "/api/points/me",
  BOOTCAMP_REVIEWS: (bootcampId: string) =>
    `/api/bootcamps/${bootcampId}/reviews`,
} as const;
