import type { Metadata } from "next";
import "./globals.css";

import MSWProvider from "@/mocks/MSWProvider";
import QueryProvider from "@/provider/QueryProvider";
import Header from "@/components/common/Header";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/common/Footer";

export const metadata: Metadata = {
  title: "Boot Talk App",
  description: "Generated by I Can Do It",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <MSWProvider>
          <QueryProvider>
            <Header />
            <main className="flex-grow min-h-[800px]">{children}</main>
            <Toaster position="top-center" toastOptions={{ duration: 3000 }} />
            <Footer />
          </QueryProvider>
        </MSWProvider>
      </body>
    </html>
  );
}
